// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xellklpjkcitwzhwdgoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlbGxrbHBqa2NpdHd6aHdkZ29pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTM1MjAsImV4cCI6MjA2OTA4OTUyMH0.1MDeTKR03w0NxkPrYbueM_CvbEcub0vskYricsx6YHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});